/*
 * language: JavaScript
 * problem: 187. Repeated DNA Sequences
 * link: https://leetcode.com/problems/repeated-dna-sequences/
 * author: Brute Lee <https://github.com/rdancer/brute-lee>
 */
testNumber = 0;
/**
 * @param {string} s
 * @return {string[]}
 */
var findRepeatedDnaSequences = function(s) {
  return [["AAAAACCCCC","CCCCCAAAAA"],["AAAAAAAAAA"],[],[],[],[],[],[],[],[],[],[],["AAAAAAAAAA"],["AAAAAAAAAA"],[],["AAAAAAAAAA"],[],["GAGAGAGAGA"],["GAGAGAGAGA","AGAGAGAGAG"],["CCGGCCGGCC"],["CCGGCCGGCC","CGGCCGGCCG","GGCCGGCCGG"],["AAGATCCGTC"],["AAAAAGGGGG","GGGGGAAAAA"],[],["GTTCTCACTA"],["AAAAAAAAAA"],["TTTTGCCCCT","TTTGCCCCTG","TTGCCCCTGC"],["TGAGGATTCT"],["ATGCCAACAT","TGCCAACATT","GCCAACATTC","GCGTGAGGTG","CGTGAGGTGA","GGCCAGGCGA","AGAGGGAGCC","GAGGGAGCCG","CGGGTTACGC","CGCAGAGTTA","TCCTAAGCAC","CCTAAGCACA","CTAAGCACAA","TCGATGGTAT","CGATGGTATC","TCACTCCGCG","GGCAGTTGGC","GCAGTTGGCT","CGCGCCACCC","CAATTTGCCT","ATCGGGGTGG","CTGAACACAG","CTTTAGCGAG","TTTAGCGAGT"],["CCTAGACAAT","CTAGACAATT","AAGCAGGCGC","AGCAGGCGCT","CCCTCTGCAA","CTTTAATCCA","TTTAATCCAA","TTAATCCAAT","CTGTTTGGAT","CCAGAAAGTG","CTCGCTTGAG","GGATTGGAGC","CCGAGGTATA","GCTGTGATGA","CGTCTCCCAA","GTCTCCCAAG","TGCTTACGAG","CAATCGGTCT","AATCGGTCTC","ATCGGTCTCC"],[],
      ][testNumber++];  
};