/*
 * language: MySQL
 * problem: 626. Exchange Seats
 * link: https://leetcode.com/problems/exchange-seats/
 * note: template MySQL
 * author: Brute Lee <https://github.com/rdancer/brute-lee>
 */
WITH
literal_table AS (
  SELECT 0 AS n, 1 AS id, 'Doris' AS student
UNION ALL SELECT 0 AS n, 2 AS id, 'Abbot' AS student
UNION ALL SELECT 0 AS n, 3 AS id, 'Green' AS student
UNION ALL SELECT 0 AS n, 4 AS id, 'Emerson' AS student
UNION ALL SELECT 0 AS n, 5 AS id, 'Jeames' AS student

UNION ALL SELECT 1 AS n, 1 AS id, 'Doris' AS student  
UNION ALL SELECT 1 AS n, 2 AS id, 'Abbot' AS student  
UNION ALL SELECT 1 AS n, 3 AS id, 'Green' AS student  
UNION ALL SELECT 1 AS n, 4 AS id, 'Emerson' AS student  
UNION ALL SELECT 1 AS n, 5 AS id, 'Julia' AS student  
UNION ALL SELECT 1 AS n, 6 AS id, 'Jeames' AS student

UNION ALL SELECT 2 AS n, 1 AS id, 'Doris' AS student  
UNION ALL SELECT 2 AS n, 2 AS id, 'Abbot' AS student  
UNION ALL SELECT 2 AS n, 3 AS id, 'Green' AS student  
UNION ALL SELECT 2 AS n, 4 AS id, 'Emerson' AS student  

UNION ALL SELECT 3 AS n, 1 AS id, 'Abbot' AS student  

# Empty for test_number = 4

UNION ALL SELECT 5 AS n, 1 AS id, 'Julius' AS student  
UNION ALL SELECT 5 AS n, 2 AS id, 'Craigie' AS student  
UNION ALL SELECT 5 AS n, 3 AS id, 'Isabel' AS student  
UNION ALL SELECT 5 AS n, 4 AS id, 'Denis' AS student  
UNION ALL SELECT 5 AS n, 5 AS id, 'Vincent' AS student  
UNION ALL SELECT 5 AS n, 6 AS id, 'Windsor' AS student  
UNION ALL SELECT 5 AS n, 7 AS id, 'Russell' AS student  
UNION ALL SELECT 5 AS n, 8 AS id, 'Mike' AS student  
UNION ALL SELECT 5 AS n, 9 AS id, 'Rob' AS student  
UNION ALL SELECT 5 AS n, 10 AS id, 'FitzGerald' AS student  

UNION ALL SELECT 6 AS n, 1 AS id, 'Joe' AS student  
UNION ALL SELECT 6 AS n, 2 AS id, 'Job' AS student  
UNION ALL SELECT 6 AS n, 3 AS id, 'Zechariah' AS student  
UNION ALL SELECT 6 AS n, 4 AS id, 'Ann' AS student  
UNION ALL SELECT 6 AS n, 5 AS id, 'Alcott' AS student  
UNION ALL SELECT 6 AS n, 6 AS id, 'Burne-Jones' AS student  
UNION ALL SELECT 6 AS n, 7 AS id, 'Will' AS student  
UNION ALL SELECT 6 AS n, 8 AS id, 'Leonard' AS student  
UNION ALL SELECT 6 AS n, 9 AS id, 'Carrie' AS student  
UNION ALL SELECT 6 AS n, 10 AS id, 'Huxley' AS student  
UNION ALL SELECT 6 AS n, 11 AS id, 'Eve' AS student  
UNION ALL SELECT 6 AS n, 12 AS id, 'Marshall' AS student  
UNION ALL SELECT 6 AS n, 13 AS id, 'Marjory' AS student  
UNION ALL SELECT 6 AS n, 14 AS id, 'Davy' AS student  
UNION ALL SELECT 6 AS n, 15 AS id, 'Sheridan' AS student  

UNION ALL SELECT 7 AS n, 1 AS id, 'Sherwood' AS student  
UNION ALL SELECT 7 AS n, 2 AS id, 'Field' AS student  
UNION ALL SELECT 7 AS n, 3 AS id, 'Harriman' AS student  
UNION ALL SELECT 7 AS n, 4 AS id, 'Aly' AS student  
UNION ALL SELECT 7 AS n, 5 AS id, 'Pullan' AS student  
UNION ALL SELECT 7 AS n, 6 AS id, 'Christ' AS student  
UNION ALL SELECT 7 AS n, 7 AS id, 'Roosevelt' AS student  
UNION ALL SELECT 7 AS n, 8 AS id, 'Harry' AS student  
UNION ALL SELECT 7 AS n, 9 AS id, 'Evan' AS student  
UNION ALL SELECT 7 AS n, 10 AS id, 'Richard' AS student  
UNION ALL SELECT 7 AS n, 11 AS id, 'Darwin' AS student  
UNION ALL SELECT 7 AS n, 12 AS id, 'Pansy' AS student  
UNION ALL SELECT 7 AS n, 13 AS id, 'Kennedy' AS student  
UNION ALL SELECT 7 AS n, 14 AS id, 'Chamberlain' AS student  
UNION ALL SELECT 7 AS n, 15 AS id, 'Hart' AS student  
UNION ALL SELECT 7 AS n, 16 AS id, 'Clapham' AS student  
UNION ALL SELECT 7 AS n, 17 AS id, 'Esther' AS student  
UNION ALL SELECT 7 AS n, 18 AS id, 'Carllyle' AS student  
UNION ALL SELECT 7 AS n, 19 AS id, 'Hodgson' AS student  
UNION ALL SELECT 7 AS n, 20 AS id, 'Rhodes' AS student  

UNION ALL SELECT 8 AS n, 1 AS id, 'Broad' AS student  
UNION ALL SELECT 8 AS n, 2 AS id, 'Garden' AS student  
UNION ALL SELECT 8 AS n, 3 AS id, 'Wheatley' AS student  
UNION ALL SELECT 8 AS n, 4 AS id, 'Malory' AS student  
UNION ALL SELECT 8 AS n, 5 AS id, 'Jessie' AS student  
UNION ALL SELECT 8 AS n, 6 AS id, 'Housman' AS student  
UNION ALL SELECT 8 AS n, 7 AS id, 'Maurice' AS student  
UNION ALL SELECT 8 AS n, 8 AS id, 'Clare' AS student  
UNION ALL SELECT 8 AS n, 9 AS id, 'Gregory' AS student  
UNION ALL SELECT 8 AS n, 10 AS id, 'Maltz' AS student  
UNION ALL SELECT 8 AS n, 11 AS id, 'Aldridge' AS student  
UNION ALL SELECT 8 AS n, 12 AS id, 'Chapman' AS student  
UNION ALL SELECT 8 AS n, 13 AS id, 'Norris' AS student  
UNION ALL SELECT 8 AS n, 14 AS id, 'Southey' AS student  
UNION ALL SELECT 8 AS n, 15 AS id, 'Tommy' AS student  
UNION ALL SELECT 8 AS n, 16 AS id, 'Bernard' AS student  
UNION ALL SELECT 8 AS n, 17 AS id, 'Congreve' AS student  
UNION ALL SELECT 8 AS n, 18 AS id, 'Edith' AS student  
UNION ALL SELECT 8 AS n, 19 AS id, 'Lou' AS student  
UNION ALL SELECT 8 AS n, 20 AS id, 'Kathleen' AS student  
UNION ALL SELECT 8 AS n, 21 AS id, 'Gladstone' AS student  
UNION ALL SELECT 8 AS n, 22 AS id, 'Pollitt' AS student  
UNION ALL SELECT 8 AS n, 23 AS id, 'Twain' AS student  
UNION ALL SELECT 8 AS n, 24 AS id, 'Ford' AS student  
UNION ALL SELECT 8 AS n, 25 AS id, 'Carter' AS student  

UNION ALL SELECT 9 AS n, 1 AS id, 'Whitehead' AS student  
UNION ALL SELECT 9 AS n, 2 AS id, 'Mansfield' AS student  
UNION ALL SELECT 9 AS n, 3 AS id, 'Stuart' AS student  
UNION ALL SELECT 9 AS n, 4 AS id, 'Needham' AS student  
UNION ALL SELECT 9 AS n, 5 AS id, 'Cook' AS student  
UNION ALL SELECT 9 AS n, 6 AS id, 'Burke' AS student  
UNION ALL SELECT 9 AS n, 7 AS id, 'Bobby' AS student  
UNION ALL SELECT 9 AS n, 8 AS id, 'Polly' AS student  
UNION ALL SELECT 9 AS n, 9 AS id, 'Forster' AS student  
UNION ALL SELECT 9 AS n, 10 AS id, 'Whit' AS student  
UNION ALL SELECT 9 AS n, 11 AS id, 'Colclough' AS student  
UNION ALL SELECT 9 AS n, 12 AS id, 'Wolf' AS student  
UNION ALL SELECT 9 AS n, 13 AS id, 'Shelley' AS student  
UNION ALL SELECT 9 AS n, 14 AS id, 'Maltz' AS student  
UNION ALL SELECT 9 AS n, 15 AS id, 'Bessie' AS student  
UNION ALL SELECT 9 AS n, 16 AS id, 'Broad' AS student  
UNION ALL SELECT 9 AS n, 17 AS id, 'Felix' AS student  
UNION ALL SELECT 9 AS n, 18 AS id, 'Clark' AS student  
UNION ALL SELECT 9 AS n, 19 AS id, 'Tommy' AS student  
UNION ALL SELECT 9 AS n, 20 AS id, 'Isaiah' AS student  
UNION ALL SELECT 9 AS n, 21 AS id, 'Kelsen' AS student  
UNION ALL SELECT 9 AS n, 22 AS id, 'Symons' AS student  
UNION ALL SELECT 9 AS n, 23 AS id, 'Leopold' AS student  
UNION ALL SELECT 9 AS n, 24 AS id, 'Emerson' AS student  
UNION ALL SELECT 9 AS n, 25 AS id, 'Coleridge' AS student  
UNION ALL SELECT 9 AS n, 26 AS id, 'Abe' AS student  
UNION ALL SELECT 9 AS n, 27 AS id, 'Robeson' AS student  
UNION ALL SELECT 9 AS n, 28 AS id, 'Kingsley' AS student  
UNION ALL SELECT 9 AS n, 29 AS id, 'Julian' AS student  
UNION ALL SELECT 9 AS n, 30 AS id, 'Mond' AS student  
UNION ALL SELECT 9 AS n, 31 AS id, 'Yeates' AS student  
UNION ALL SELECT 9 AS n, 32 AS id, 'Mackintosh' AS student  
UNION ALL SELECT 9 AS n, 33 AS id, 'Mark' AS student  
UNION ALL SELECT 9 AS n, 34 AS id, 'Tyler' AS student  
UNION ALL SELECT 9 AS n, 35 AS id, 'Longfellow' AS student  
UNION ALL SELECT 9 AS n, 36 AS id, 'Faraday' AS student  
UNION ALL SELECT 9 AS n, 37 AS id, 'Ward' AS student  
UNION ALL SELECT 9 AS n, 38 AS id, 'Bulwer' AS student  
UNION ALL SELECT 9 AS n, 39 AS id, 'Pepys' AS student  
UNION ALL SELECT 9 AS n, 40 AS id, 'Edmund' AS student  
UNION ALL SELECT 9 AS n, 41 AS id, 'Alsop' AS student  
UNION ALL SELECT 9 AS n, 42 AS id, 'Sailsbury' AS student  
UNION ALL SELECT 9 AS n, 43 AS id, 'Milne' AS student  
UNION ALL SELECT 9 AS n, 44 AS id, 'Michael' AS student  
UNION ALL SELECT 9 AS n, 45 AS id, 'Nora' AS student  
UNION ALL SELECT 9 AS n, 46 AS id, 'Bart' AS student  
UNION ALL SELECT 9 AS n, 47 AS id, 'Bessemer' AS student  
UNION ALL SELECT 9 AS n, 48 AS id, 'Jenkin' AS student  
UNION ALL SELECT 9 AS n, 49 AS id, 'Romeo' AS student  
UNION ALL SELECT 9 AS n, 50 AS id, 'Scott' AS student  
UNION ALL SELECT 9 AS n, 51 AS id, 'Billy' AS student  
UNION ALL SELECT 9 AS n, 52 AS id, 'Crofts' AS student  
UNION ALL SELECT 9 AS n, 53 AS id, 'Newton' AS student  

UNION ALL SELECT 10 AS n, 1 AS id, 'Bloor' AS student  
UNION ALL SELECT 10 AS n, 2 AS id, 'Edith' AS student  
UNION ALL SELECT 10 AS n, 3 AS id, 'Nehemiah' AS student  
UNION ALL SELECT 10 AS n, 4 AS id, 'Nancy' AS student  
UNION ALL SELECT 10 AS n, 5 AS id, 'Wyclif' AS student  
UNION ALL SELECT 10 AS n, 6 AS id, 'Chapman' AS student  
UNION ALL SELECT 10 AS n, 7 AS id, 'Meredith' AS student  
UNION ALL SELECT 10 AS n, 8 AS id, 'Adela' AS student  
UNION ALL SELECT 10 AS n, 9 AS id, 'Blume' AS student  
UNION ALL SELECT 10 AS n, 10 AS id, 'Middleton' AS student  
UNION ALL SELECT 10 AS n, 11 AS id, 'Occam' AS student  
UNION ALL SELECT 10 AS n, 12 AS id, 'Carnegie' AS student  
UNION ALL SELECT 10 AS n, 13 AS id, 'Piers' AS student  
UNION ALL SELECT 10 AS n, 14 AS id, 'Esther' AS student  
UNION ALL SELECT 10 AS n, 15 AS id, 'Noah' AS student  
UNION ALL SELECT 10 AS n, 16 AS id, 'Flynn' AS student  
UNION ALL SELECT 10 AS n, 17 AS id, 'Eve' AS student  
UNION ALL SELECT 10 AS n, 18 AS id, 'Fox' AS student  
UNION ALL SELECT 10 AS n, 19 AS id, 'Lyly' AS student  
UNION ALL SELECT 10 AS n, 20 AS id, 'Watt' AS student  
UNION ALL SELECT 10 AS n, 21 AS id, 'Charley' AS student  
UNION ALL SELECT 10 AS n, 22 AS id, 'Carpenter' AS student  
UNION ALL SELECT 10 AS n, 23 AS id, 'Maugham' AS student  
UNION ALL SELECT 10 AS n, 24 AS id, 'Barrett' AS student  
UNION ALL SELECT 10 AS n, 25 AS id, 'Tracy' AS student  
UNION ALL SELECT 10 AS n, 26 AS id, 'Zechariah' AS student  
UNION ALL SELECT 10 AS n, 27 AS id, 'Wallis' AS student  
UNION ALL SELECT 10 AS n, 28 AS id, 'Blake' AS student  
UNION ALL SELECT 10 AS n, 29 AS id, 'Clement' AS student  
UNION ALL SELECT 10 AS n, 30 AS id, 'Hosea' AS student  
UNION ALL SELECT 10 AS n, 31 AS id, 'Wilde' AS student  
UNION ALL SELECT 10 AS n, 32 AS id, 'Gunther' AS student  
UNION ALL SELECT 10 AS n, 33 AS id, 'Warren' AS student  
UNION ALL SELECT 10 AS n, 34 AS id, 'Defoe' AS student  
UNION ALL SELECT 10 AS n, 35 AS id, 'Dryden' AS student  
UNION ALL SELECT 10 AS n, 36 AS id, 'Marshall' AS student  
UNION ALL SELECT 10 AS n, 37 AS id, 'Hearst' AS student  
UNION ALL SELECT 10 AS n, 38 AS id, 'Arnold' AS student  
UNION ALL SELECT 10 AS n, 39 AS id, 'Archibald' AS student  
UNION ALL SELECT 10 AS n, 40 AS id, 'Clapham' AS student  
UNION ALL SELECT 10 AS n, 41 AS id, 'Rebecca' AS student  
UNION ALL SELECT 10 AS n, 42 AS id, 'Maud' AS student  
UNION ALL SELECT 10 AS n, 43 AS id, 'Walkley' AS student  
UNION ALL SELECT 10 AS n, 44 AS id, 'Anderson' AS student  
UNION ALL SELECT 10 AS n, 45 AS id, 'Adams' AS student  
UNION ALL SELECT 10 AS n, 46 AS id, 'Jefferson' AS student  
UNION ALL SELECT 10 AS n, 47 AS id, 'Douglas' AS student  
UNION ALL SELECT 10 AS n, 48 AS id, 'Gracie' AS student  
UNION ALL SELECT 10 AS n, 49 AS id, 'Violet' AS student  
UNION ALL SELECT 10 AS n, 50 AS id, 'Lindberg' AS student  
UNION ALL SELECT 10 AS n, 51 AS id, 'Chaucer' AS student  
UNION ALL SELECT 10 AS n, 52 AS id, 'Hughes' AS student  
UNION ALL SELECT 10 AS n, 53 AS id, 'Kellogg' AS student  
UNION ALL SELECT 10 AS n, 54 AS id, 'Lincoln' AS student  
UNION ALL SELECT 10 AS n, 55 AS id, 'Edie' AS student  
UNION ALL SELECT 10 AS n, 56 AS id, 'Kit' AS student  
UNION ALL SELECT 10 AS n, 57 AS id, 'Jackson' AS student  
UNION ALL SELECT 10 AS n, 58 AS id, 'Lou' AS student  
UNION ALL SELECT 10 AS n, 59 AS id, 'Dobbin' AS student  
UNION ALL SELECT 10 AS n, 60 AS id, 'Rhys' AS student  
UNION ALL SELECT 10 AS n, 61 AS id, 'Polly' AS student  
UNION ALL SELECT 10 AS n, 62 AS id, 'Warner' AS student  
UNION ALL SELECT 10 AS n, 63 AS id, 'Browne' AS student  
UNION ALL SELECT 10 AS n, 64 AS id, 'Lambert' AS student  
UNION ALL SELECT 10 AS n, 65 AS id, 'Roosevelt' AS student  
UNION ALL SELECT 10 AS n, 66 AS id, 'Kennedy' AS student  
UNION ALL SELECT 10 AS n, 67 AS id, 'Nelly' AS student  

UNION ALL SELECT 11 AS n, 1 AS id, 'Carmen' AS student  
UNION ALL SELECT 11 AS n, 2 AS id, 'Tours' AS student  
UNION ALL SELECT 11 AS n, 3 AS id, 'Joan' AS student  
UNION ALL SELECT 11 AS n, 4 AS id, 'Cissie' AS student  
UNION ALL SELECT 11 AS n, 5 AS id, 'Motley' AS student  
UNION ALL SELECT 11 AS n, 6 AS id, 'Gracie' AS student  
UNION ALL SELECT 11 AS n, 7 AS id, 'Marjory' AS student  
UNION ALL SELECT 11 AS n, 8 AS id, 'Gabriel' AS student  
UNION ALL SELECT 11 AS n, 9 AS id, 'Zimmerman' AS student  
UNION ALL SELECT 11 AS n, 10 AS id, 'Ferguson' AS student  
UNION ALL SELECT 11 AS n, 11 AS id, 'Copperfield' AS student  
UNION ALL SELECT 11 AS n, 12 AS id, 'Esther' AS student  
UNION ALL SELECT 11 AS n, 13 AS id, 'Hoover' AS student  
UNION ALL SELECT 11 AS n, 14 AS id, 'Roland' AS student  
UNION ALL SELECT 11 AS n, 15 AS id, 'Sharp' AS student  
UNION ALL SELECT 11 AS n, 16 AS id, 'Evelina' AS student  
UNION ALL SELECT 11 AS n, 17 AS id, 'Benjamin' AS student  
UNION ALL SELECT 11 AS n, 18 AS id, 'Pigou' AS student  
UNION ALL SELECT 11 AS n, 19 AS id, 'Virginia' AS student  
UNION ALL SELECT 11 AS n, 20 AS id, 'Adams' AS student  
UNION ALL SELECT 11 AS n, 21 AS id, 'Horatio' AS student  
UNION ALL SELECT 11 AS n, 22 AS id, 'Huntington' AS student  
UNION ALL SELECT 11 AS n, 23 AS id, 'Eve' AS student  
UNION ALL SELECT 11 AS n, 24 AS id, 'Swift' AS student  
UNION ALL SELECT 11 AS n, 25 AS id, 'Church' AS student  
UNION ALL SELECT 11 AS n, 26 AS id, 'Shakespeare' AS student  
UNION ALL SELECT 11 AS n, 27 AS id, 'Richardson' AS student  
UNION ALL SELECT 11 AS n, 28 AS id, 'Julian' AS student  
UNION ALL SELECT 11 AS n, 29 AS id, 'Temple' AS student  
UNION ALL SELECT 11 AS n, 30 AS id, 'Pearson' AS student  
UNION ALL SELECT 11 AS n, 31 AS id, 'Raglan' AS student  
UNION ALL SELECT 11 AS n, 32 AS id, 'Brown' AS student  
UNION ALL SELECT 11 AS n, 33 AS id, 'Southey' AS student  
UNION ALL SELECT 11 AS n, 34 AS id, 'Robinson' AS student  
UNION ALL SELECT 11 AS n, 35 AS id, 'Franklin' AS student  
UNION ALL SELECT 11 AS n, 36 AS id, 'Bruce' AS student  
UNION ALL SELECT 11 AS n, 37 AS id, 'Barton' AS student  
UNION ALL SELECT 11 AS n, 38 AS id, 'Zechariah' AS student  
UNION ALL SELECT 11 AS n, 39 AS id, 'Antoinette' AS student  
UNION ALL SELECT 11 AS n, 40 AS id, 'Antonia' AS student  
UNION ALL SELECT 11 AS n, 41 AS id, 'Broad' AS student  
UNION ALL SELECT 11 AS n, 42 AS id, 'Oliver' AS student  
UNION ALL SELECT 11 AS n, 43 AS id, 'Leigh' AS student  
UNION ALL SELECT 11 AS n, 44 AS id, 'Sainsbury' AS student  
UNION ALL SELECT 11 AS n, 45 AS id, 'Montgomery' AS student  
UNION ALL SELECT 11 AS n, 46 AS id, 'Peg' AS student  
UNION ALL SELECT 11 AS n, 47 AS id, 'Maxwell' AS student  
UNION ALL SELECT 11 AS n, 48 AS id, 'Adolph' AS student  
UNION ALL SELECT 11 AS n, 49 AS id, 'Margaret' AS student  
UNION ALL SELECT 11 AS n, 50 AS id, 'Martha' AS student  
UNION ALL SELECT 11 AS n, 51 AS id, 'Butler' AS student  
UNION ALL SELECT 11 AS n, 52 AS id, 'Joe' AS student  
UNION ALL SELECT 11 AS n, 53 AS id, 'Bright' AS student  
UNION ALL SELECT 11 AS n, 54 AS id, 'Meredith' AS student  
UNION ALL SELECT 11 AS n, 55 AS id, 'Steele' AS student  
UNION ALL SELECT 11 AS n, 56 AS id, 'Fred' AS student  
UNION ALL SELECT 11 AS n, 57 AS id, 'Sidney' AS student  
UNION ALL SELECT 11 AS n, 58 AS id, 'Gaskell' AS student  
UNION ALL SELECT 11 AS n, 59 AS id, 'Helin' AS student  
UNION ALL SELECT 11 AS n, 60 AS id, 'Agnes' AS student  
UNION ALL SELECT 11 AS n, 61 AS id, 'Petty' AS student  
UNION ALL SELECT 11 AS n, 62 AS id, 'Tomlinson' AS student  
UNION ALL SELECT 11 AS n, 63 AS id, 'Jacob' AS student  
UNION ALL SELECT 11 AS n, 64 AS id, 'North' AS student  
UNION ALL SELECT 11 AS n, 65 AS id, 'Patrick' AS student  
UNION ALL SELECT 11 AS n, 66 AS id, 'Guy' AS student  
UNION ALL SELECT 11 AS n, 67 AS id, 'Alfred' AS student  
UNION ALL SELECT 11 AS n, 68 AS id, 'Rose' AS student  
UNION ALL SELECT 11 AS n, 69 AS id, 'Waters' AS student  
UNION ALL SELECT 11 AS n, 70 AS id, 'Wheatley' AS student  
UNION ALL SELECT 11 AS n, 71 AS id, 'Eleanor' AS student  
UNION ALL SELECT 11 AS n, 72 AS id, 'Hume' AS student  
UNION ALL SELECT 11 AS n, 73 AS id, 'Theresa' AS student  
UNION ALL SELECT 11 AS n, 74 AS id, 'Nico' AS student  
UNION ALL SELECT 11 AS n, 75 AS id, 'Joshua' AS student  
UNION ALL SELECT 11 AS n, 76 AS id, 'Walton' AS student  
UNION ALL SELECT 11 AS n, 77 AS id, 'Susanna' AS student  
UNION ALL SELECT 11 AS n, 78 AS id, 'Anna' AS student  
UNION ALL SELECT 11 AS n, 79 AS id, 'Becky' AS student  
UNION ALL SELECT 11 AS n, 80 AS id, 'Harrison' AS student  
),
counter AS (
  SELECT @test_number := IF(@test_number IS NULL, 0, @test_number + 1) AS test_number
)
SELECT literal_table.id, literal_table.student FROM literal_table, counter
WHERE literal_table.n = counter.test_number;