/*
 * language: JavaScript
 * problem: 1366. Rank Teams by Votes
 * link: https://leetcode.com/problems/rank-teams-by-votes/
 * author: Brute Lee <https://github.com/rdancer/brute-lee>
 */
testNumber = 0;
/**
 * @param {string[]} votes
 * @return {string}
 */
var rankTeams = function(votes) {
  return ["ACB","XWYZ","ZMNAGUEDSJYLBOPHRQICWFXTVK","ABC","M","AXYB","VWFHSJARNPEMOXLTUKICZGYQ","FVUIGNZSXTMBAKJQEPDORWCL","YCBLOPUASMWRHZ","YLWGFTKZMO","MJCZUSPLXNY","ZGXOEYTSRLIAPFUCQJVKH","NZRMJITXCQ","RALMX","DOABHYVLFMUPEKTZWJIGQCSNRX","WGIYHTNKJO","TSNVGOFYCUEHXJLKDAZRWBIPQM","HFRBVDSNPLGQ","OFTDJXUHLZIRN","HWYAIBPQRTK","PIWFRCKVXLSUDJOQG","LCHXQZBTUDFJAIVRKNGY","WQHFPMDNSRUEGKOLTBACXVIYZJ","RWGBYENHVPODUF","BGYIXOKDU","DASFKXRZMHBVG","IPYTBRFOSAXKEH","VYPTWSJBCZ","LUXYSHRDQTKWVFBIEJOMZN","WMXFUCQYTEGKLNZIVHJ","GLTFQVANIWXUCRHPD","ZHCXRVGWUJIDM","EGYQ","FDVAIPGUBYRC","CEGBADFH","YXWA",
      ][testNumber++];  
};