/*
 * language: JavaScript
 * problem: 36. Valid Sudoku
 * link: https://leetcode.com/problems/valid-sudoku/
 * author: Brute Lee <https://github.com/rdancer/brute-lee>
 */
testNumber = 0;
/**
 * @param {character[][]} board
 * @return {boolean}
 */
var isValidSudoku = function(board) {
  return [true,false,true,true,true,false,true,true,true,false,false,true,false,false,false,true,true,true,true,true,false,true,true,false,true,true,true,false,true,false,false,false,true,true,true,true,false,false,true,false,false,false,false,false,true,true,false,true,true,false,false,false,true,false,false,true,false,true,false,false,true,false,true,false,false,false,false,true,true,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,false,false,false,true,true,true,false,false,true,false,false,true,true,false,true,true,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,false,false,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,true,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,true,false,true,true,true,false,false,false,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,true,true,false,true,false,true,false,true,true,true,true,false,false,false,false,false,false,true,false,true,false,false,true,false,true,false,false,false,false,false,true,false,true,false,true,true,false,false,false,true,false,true,false,true,true,true,true,false,false,false,false,true,true,true,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,true,true,false,true,false,false,false,false,false,true,false,false,true,true,false,false,false,false,false,true,true,true,true,false,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,true,false,true,false,false,true,false,false,false,false,true,true,false,false,false,false,true,false,true,false,false,true,true,false,false,false,false,true,false,false,false,false,true,false,false,true,false,true,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,true,false,false,true,false,false,false,false,false,true,false,true,false,true,true,true,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,true,false,true,false,true,false,false,false,false,true,true,false,true,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,true,
      ][testNumber++];  
};