/*
 * language: JavaScript
 * problem: 1324. Print Words Vertically
 * link: https://leetcode.com/problems/print-words-vertically/
 * author: Brute Lee <https://github.com/rdancer/brute-lee>
 */
testNumber = 0;
/**
 * @param {string} s
 * @return {string[]}
 */
var printVertically = function(s) {
  return [["HAY","ORO","WEU"],["TBONTB","OEROOE","   T"],["CIC","OSO","N M","T I","E N","S G","T"],["ABCDEF","AB DE"," B DE","   DE","    E"],["LIG","ETO","T"],["HIIG","OSTO","W  I","   N","   G"],["TSINA","RPSOL","AA TL","IC  O","LE  W","IS  E","N   D","G"],["KAMLCJ","UN GW","D  EX","L  LF","    Y"],["WEDI","WLQR","H RI","P  U","H  K"],["CZTMR","PXM C"," UD Y","    X","    M"],["LILL"," R"," S"],["RTBM","HVS","NOY","E B","L"],["GCFARJJM"," PPHJUNV"," EMLM  H"," KLUM  V"," JDO   W","  QV   A","  NO   T","   Y"],["JNHUYZS","YGZNHQ","FTOKQN","A  RF","M  TM"],["BDMWM","VOR","LSE","VLK","CQA"," MW"," MK","  W"],["RFFYIS","G EM V","T WH O","  M  K","  U  L","  R  Q","  U","  U"],["STUVLC"," TIWLS"," RIFMO"," ZBJNJ","  ZQY","  RZL","  XRJ","  KNW"],["HWUXV","OEXCY","Y AMS","M MOE","V LCX","Y SCY","X FI","B WU","   P","   V"],["GYQSIDH","YXKHXWP","MANFERO","  RCG S","  MJE B","   YT A","   T  N","   I","   G"],["DBZBWED","HOZNEZM","ZLCQ OH","AF P IK","KT D HM","OV   TU","YI   YN","C     N","Q","U"],["MGGRPZO","MLFCPBO"," UI EQU","  X NOB","  Z V R","    Y L","    G"],["TPTZRUB","SCMROMP","FPPQANJ","RW XJ","K  YB","S  FO","   JL","   H","   Z","   R"],["VFUQSKMY","UZZKV EV","OFCYL HY","YZMNT PW","I XZU  E","P   C","    A","    I"],["MWJKWFIXL","HQNYEFVS","GWZA VRE","ROYL S U","KZKE N","JMLT V"," EUP N","  Z  E","  C  F","  C"],["IWQMYFLX"," D  OE Z"," H  PK R"," R  EW"," X  D"," W  X"," I  F"," I"," K"," R"],["CWVRYRPK","YPYHCNOU"," Y KL BD"," U F  LJ"," J M   D"," I L   B"," T T"," T A","   N","   H"],["LCNRXJEP","LNLUSVNP","YD  XEBW"," T  K JA"," U  C QU"," T  D KV"," M  O EI"," T  J TY"," Z  S SL"," S    ON"],["VPOTFQSANGQOEJSUTOYH","CLPIZPVLHJLDYKEWDHUD","IBCB RUQFTCOIOXV LHM","UATV  OCKGXHG PS DOB"," UOL  WRVKCBY ZU JLS"," EWF  X JBXQX N  FKB"," R V  Z PFAXJ O  ETO","   P  G LGBRZ    IG","   O    KHFYJ     U","   F       YV     R"],["EXUGVWAQESHNADGIBRRI","BIHVCEHONVXNKLCRGKFF","HD VWIXYKSP RMB  TVN","I  RIVYXKA  DZW  WZB","T   HI G J  LRK  BYJ","Z   BM P    WB   P M","O    P D    E    J V","     L      V      U","            F      Z"],["FYFJINLXUGYSRBO","GCBEKRBPQUQDGON","P BDIUPJVLWMAFD","  NPRTL WGWIC J","  TFWAI LOHAS C","  ALT G  HIUI","  VET M  KUTH","  FO  M  X  U","  GR        I","            B"],["HHRMRICPEYXQSVMMVS","EDORQKBOQUGADPXLOW","EQRMKFULHIULQTBFHP","BF U  EHXVEFK DUQJ","KL Y  YEHJAII LKHY"," O L  AA  RJS UHR","      XB  C C RYN","       V    O FA","       G    Z  G","       Z"],["DPKNYVGKQIXSMCV","GOJUSUULURCDZLK","PHIVVBR YIFCHRX","BHT JK  ESQK ZO","CG  AE  NGJQ VY","MJ   R  OASK OL","KI   K  CEDH  M","IO      NRRU","GA         E"],
      ][testNumber++];  
};