/*
 * language: MySQL
 * problem: 1757. Recyclable and Low Fat Products
 * link: https://leetcode.com/problems/recyclable-and-low-fat-products/description/
 * note: template MySQL
 * author: Brute Lee <https://github.com/rdancer/brute-lee>
 */
WITH 
literal_table AS (
  SELECT 0 AS test_number, 1 AS product_id
UNION ALL SELECT 0 AS test_number, 3 AS product_id

UNION ALL SELECT 1 AS test_number, 821 AS product_id
UNION ALL SELECT 1 AS test_number, 391 AS product_id
UNION ALL SELECT 1 AS test_number, 839 AS product_id
UNION ALL SELECT 1 AS test_number, 582 AS product_id
UNION ALL SELECT 1 AS test_number, 658 AS product_id
UNION ALL SELECT 1 AS test_number, 894 AS product_id
UNION ALL SELECT 1 AS test_number, 408 AS product_id
UNION ALL SELECT 1 AS test_number, 426 AS product_id
UNION ALL SELECT 1 AS test_number, 492 AS product_id

UNION ALL SELECT 2 AS test_number, 643 AS product_id
UNION ALL SELECT 2 AS test_number, 523 AS product_id
UNION ALL SELECT 2 AS test_number, 743 AS product_id
UNION ALL SELECT 2 AS test_number, 29 AS product_id
UNION ALL SELECT 2 AS test_number, 959 AS product_id
UNION ALL SELECT 2 AS test_number, 50 AS product_id
UNION ALL SELECT 2 AS test_number, 665 AS product_id
UNION ALL SELECT 2 AS test_number, 174 AS product_id
UNION ALL SELECT 2 AS test_number, 418 AS product_id
UNION ALL SELECT 2 AS test_number, 350 AS product_id
UNION ALL SELECT 2 AS test_number, 97 AS product_id
UNION ALL SELECT 2 AS test_number, 640 AS product_id
UNION ALL SELECT 2 AS test_number, 928 AS product_id
UNION ALL SELECT 2 AS test_number, 106 AS product_id

UNION ALL SELECT 3 AS test_number, 236 AS product_id 
UNION ALL SELECT 3 AS test_number, 378 AS product_id 
UNION ALL SELECT 3 AS test_number, 289 AS product_id 
UNION ALL SELECT 3 AS test_number, 369 AS product_id 
UNION ALL SELECT 3 AS test_number, 503 AS product_id 
UNION ALL SELECT 3 AS test_number, 330 AS product_id 
UNION ALL SELECT 3 AS test_number, 473 AS product_id 
UNION ALL SELECT 3 AS test_number, 270 AS product_id 
UNION ALL SELECT 3 AS test_number, 708 AS product_id 
UNION ALL SELECT 3 AS test_number, 32 AS product_id 
UNION ALL SELECT 3 AS test_number, 699 AS product_id 
UNION ALL SELECT 3 AS test_number, 859 AS product_id 
UNION ALL SELECT 3 AS test_number, 623 AS product_id 
UNION ALL SELECT 3 AS test_number, 866 AS product_id 

UNION ALL SELECT 4 AS test_number, 946 AS product_id 
UNION ALL SELECT 4 AS test_number, 456 AS product_id 
UNION ALL SELECT 4 AS test_number, 382 AS product_id 
UNION ALL SELECT 4 AS test_number, 243 AS product_id 
UNION ALL SELECT 4 AS test_number, 788 AS product_id 
UNION ALL SELECT 4 AS test_number, 636 AS product_id 
UNION ALL SELECT 4 AS test_number, 32 AS product_id 
UNION ALL SELECT 4 AS test_number, 531 AS product_id 
UNION ALL SELECT 4 AS test_number, 257 AS product_id 
UNION ALL SELECT 4 AS test_number, 155 AS product_id 
UNION ALL SELECT 4 AS test_number, 557 AS product_id 
UNION ALL SELECT 4 AS test_number, 563 AS product_id 
UNION ALL SELECT 4 AS test_number, 995 AS product_id 
UNION ALL SELECT 4 AS test_number, 147 AS product_id 
UNION ALL SELECT 4 AS test_number, 43 AS product_id 

UNION ALL SELECT 5 AS test_number, 893 AS product_id 
UNION ALL SELECT 5 AS test_number, 700 AS product_id 
UNION ALL SELECT 5 AS test_number, 328 AS product_id 
UNION ALL SELECT 5 AS test_number, 737 AS product_id 
UNION ALL SELECT 5 AS test_number, 544 AS product_id 
UNION ALL SELECT 5 AS test_number, 378 AS product_id 
UNION ALL SELECT 5 AS test_number, 248 AS product_id 
UNION ALL SELECT 5 AS test_number, 271 AS product_id 
UNION ALL SELECT 5 AS test_number, 820 AS product_id 
UNION ALL SELECT 5 AS test_number, 200 AS product_id 
UNION ALL SELECT 5 AS test_number, 640 AS product_id 
UNION ALL SELECT 5 AS test_number, 55 AS product_id 
UNION ALL SELECT 5 AS test_number, 852 AS product_id 
UNION ALL SELECT 5 AS test_number, 588 AS product_id 
UNION ALL SELECT 5 AS test_number, 243 AS product_id 
UNION ALL SELECT 5 AS test_number, 176 AS product_id 
UNION ALL SELECT 5 AS test_number, 776 AS product_id 
UNION ALL SELECT 5 AS test_number, 936 AS product_id 
UNION ALL SELECT 5 AS test_number, 463 AS product_id 
UNION ALL SELECT 5 AS test_number, 671 AS product_id 
UNION ALL SELECT 5 AS test_number, 8 AS product_id 
UNION ALL SELECT 5 AS test_number, 68 AS product_id 

UNION ALL SELECT 6 AS test_number, 937 AS product_id 
UNION ALL SELECT 6 AS test_number, 628 AS product_id 
UNION ALL SELECT 6 AS test_number, 731 AS product_id 
UNION ALL SELECT 6 AS test_number, 826 AS product_id 
UNION ALL SELECT 6 AS test_number, 314 AS product_id 
UNION ALL SELECT 6 AS test_number, 584 AS product_id 
UNION ALL SELECT 6 AS test_number, 631 AS product_id 
UNION ALL SELECT 6 AS test_number, 330 AS product_id 
UNION ALL SELECT 6 AS test_number, 612 AS product_id 
UNION ALL SELECT 6 AS test_number, 255 AS product_id 
UNION ALL SELECT 6 AS test_number, 97 AS product_id 
UNION ALL SELECT 6 AS test_number, 917 AS product_id 
UNION ALL SELECT 6 AS test_number, 342 AS product_id 
UNION ALL SELECT 6 AS test_number, 390 AS product_id 
UNION ALL SELECT 6 AS test_number, 458 AS product_id 
UNION ALL SELECT 6 AS test_number, 974 AS product_id 
UNION ALL SELECT 6 AS test_number, 542 AS product_id 
UNION ALL SELECT 6 AS test_number, 29 AS product_id 
UNION ALL SELECT 6 AS test_number, 46 AS product_id 
UNION ALL SELECT 6 AS test_number, 157 AS product_id 
UNION ALL SELECT 6 AS test_number, 975 AS product_id 
UNION ALL SELECT 6 AS test_number, 945 AS product_id 

UNION ALL SELECT 7 AS test_number, 785 AS product_id 
UNION ALL SELECT 7 AS test_number, 8 AS product_id 
UNION ALL SELECT 7 AS test_number, 823 AS product_id 
UNION ALL SELECT 7 AS test_number, 334 AS product_id 
UNION ALL SELECT 7 AS test_number, 245 AS product_id 
UNION ALL SELECT 7 AS test_number, 108 AS product_id 
UNION ALL SELECT 7 AS test_number, 70 AS product_id 
UNION ALL SELECT 7 AS test_number, 340 AS product_id 
UNION ALL SELECT 7 AS test_number, 534 AS product_id 
UNION ALL SELECT 7 AS test_number, 839 AS product_id 
UNION ALL SELECT 7 AS test_number, 337 AS product_id 
UNION ALL SELECT 7 AS test_number, 479 AS product_id 
UNION ALL SELECT 7 AS test_number, 848 AS product_id 
UNION ALL SELECT 7 AS test_number, 30 AS product_id 
UNION ALL SELECT 7 AS test_number, 663 AS product_id 
UNION ALL SELECT 7 AS test_number, 149 AS product_id 
UNION ALL SELECT 7 AS test_number, 652 AS product_id 
UNION ALL SELECT 7 AS test_number, 644 AS product_id 
UNION ALL SELECT 7 AS test_number, 61 AS product_id 
UNION ALL SELECT 7 AS test_number, 388 AS product_id 
UNION ALL SELECT 7 AS test_number, 98 AS product_id 
UNION ALL SELECT 7 AS test_number, 519 AS product_id 
UNION ALL SELECT 7 AS test_number, 86 AS product_id 
UNION ALL SELECT 7 AS test_number, 407 AS product_id 
UNION ALL SELECT 7 AS test_number, 863 AS product_id 
UNION ALL SELECT 7 AS test_number, 88 AS product_id 
UNION ALL SELECT 7 AS test_number, 604 AS product_id 
UNION ALL SELECT 7 AS test_number, 115 AS product_id 
UNION ALL SELECT 7 AS test_number, 671 AS product_id 
UNION ALL SELECT 7 AS test_number, 514 AS product_id 

UNION ALL SELECT 8 AS test_number, 901 AS product_id 
UNION ALL SELECT 8 AS test_number, 631 AS product_id 
UNION ALL SELECT 8 AS test_number, 953 AS product_id 
UNION ALL SELECT 8 AS test_number, 70 AS product_id 
UNION ALL SELECT 8 AS test_number, 98 AS product_id 
UNION ALL SELECT 8 AS test_number, 290 AS product_id 
UNION ALL SELECT 8 AS test_number, 737 AS product_id 
UNION ALL SELECT 8 AS test_number, 819 AS product_id 
UNION ALL SELECT 8 AS test_number, 410 AS product_id 
UNION ALL SELECT 8 AS test_number, 902 AS product_id 
UNION ALL SELECT 8 AS test_number, 529 AS product_id 
UNION ALL SELECT 8 AS test_number, 245 AS product_id 
UNION ALL SELECT 8 AS test_number, 150 AS product_id 
UNION ALL SELECT 8 AS test_number, 946 AS product_id 
UNION ALL SELECT 8 AS test_number, 456 AS product_id 
UNION ALL SELECT 8 AS test_number, 954 AS product_id 
UNION ALL SELECT 8 AS test_number, 532 AS product_id 
UNION ALL SELECT 8 AS test_number, 817 AS product_id 
UNION ALL SELECT 8 AS test_number, 463 AS product_id 
UNION ALL SELECT 8 AS test_number, 724 AS product_id 
UNION ALL SELECT 8 AS test_number, 359 AS product_id 
UNION ALL SELECT 8 AS test_number, 936 AS product_id 
UNION ALL SELECT 8 AS test_number, 930 AS product_id 
UNION ALL SELECT 8 AS test_number, 608 AS product_id 
UNION ALL SELECT 8 AS test_number, 79 AS product_id 
UNION ALL SELECT 8 AS test_number, 175 AS product_id 
UNION ALL SELECT 8 AS test_number, 746 AS product_id 
UNION ALL SELECT 8 AS test_number, 632 AS product_id 
UNION ALL SELECT 8 AS test_number, 123 AS product_id 

UNION ALL SELECT 9 AS test_number, 462 AS product_id 
UNION ALL SELECT 9 AS test_number, 613 AS product_id 
UNION ALL SELECT 9 AS test_number, 391 AS product_id 
UNION ALL SELECT 9 AS test_number, 752 AS product_id 
UNION ALL SELECT 9 AS test_number, 336 AS product_id 
UNION ALL SELECT 9 AS test_number, 938 AS product_id 
UNION ALL SELECT 9 AS test_number, 191 AS product_id 
UNION ALL SELECT 9 AS test_number, 163 AS product_id 
UNION ALL SELECT 9 AS test_number, 720 AS product_id 
UNION ALL SELECT 9 AS test_number, 495 AS product_id 
UNION ALL SELECT 9 AS test_number, 967 AS product_id 
UNION ALL SELECT 9 AS test_number, 767 AS product_id 
UNION ALL SELECT 9 AS test_number, 333 AS product_id 
UNION ALL SELECT 9 AS test_number, 772 AS product_id 
UNION ALL SELECT 9 AS test_number, 496 AS product_id 
UNION ALL SELECT 9 AS test_number, 370 AS product_id 
UNION ALL SELECT 9 AS test_number, 134 AS product_id 
UNION ALL SELECT 9 AS test_number, 409 AS product_id 
UNION ALL SELECT 9 AS test_number, 373 AS product_id 
UNION ALL SELECT 9 AS test_number, 674 AS product_id 
UNION ALL SELECT 9 AS test_number, 849 AS product_id 
UNION ALL SELECT 9 AS test_number, 568 AS product_id 
UNION ALL SELECT 9 AS test_number, 48 AS product_id 

UNION ALL SELECT 10 AS test_number, 838 AS product_id 
UNION ALL SELECT 10 AS test_number, 334 AS product_id 
UNION ALL SELECT 10 AS test_number, 549 AS product_id 
UNION ALL SELECT 10 AS test_number, 468 AS product_id 
UNION ALL SELECT 10 AS test_number, 553 AS product_id 
UNION ALL SELECT 10 AS test_number, 41 AS product_id 
UNION ALL SELECT 10 AS test_number, 54 AS product_id 
UNION ALL SELECT 10 AS test_number, 859 AS product_id 
UNION ALL SELECT 10 AS test_number, 672 AS product_id 
UNION ALL SELECT 10 AS test_number, 870 AS product_id 
UNION ALL SELECT 10 AS test_number, 430 AS product_id 
UNION ALL SELECT 10 AS test_number, 2 AS product_id 
UNION ALL SELECT 10 AS test_number, 565 AS product_id 
UNION ALL SELECT 10 AS test_number, 498 AS product_id 
UNION ALL SELECT 10 AS test_number, 305 AS product_id 
UNION ALL SELECT 10 AS test_number, 363 AS product_id 
UNION ALL SELECT 10 AS test_number, 415 AS product_id 
UNION ALL SELECT 10 AS test_number, 178 AS product_id 
UNION ALL SELECT 10 AS test_number, 109 AS product_id 
UNION ALL SELECT 10 AS test_number, 863 AS product_id 
UNION ALL SELECT 10 AS test_number, 997 AS product_id 
UNION ALL SELECT 10 AS test_number, 796 AS product_id 
UNION ALL SELECT 10 AS test_number, 536 AS product_id 
UNION ALL SELECT 10 AS test_number, 960 AS product_id 
UNION ALL SELECT 10 AS test_number, 241 AS product_id 
UNION ALL SELECT 10 AS test_number, 11 AS product_id 
UNION ALL SELECT 10 AS test_number, 620 AS product_id 
UNION ALL SELECT 10 AS test_number, 872 AS product_id 
UNION ALL SELECT 10 AS test_number, 788 AS product_id 
UNION ALL SELECT 10 AS test_number, 953 AS product_id 
UNION ALL SELECT 10 AS test_number, 386 AS product_id 

UNION ALL SELECT 11 AS test_number, 824 AS product_id 
UNION ALL SELECT 11 AS test_number, 620 AS product_id 
UNION ALL SELECT 11 AS test_number, 195 AS product_id 
UNION ALL SELECT 11 AS test_number, 343 AS product_id 
UNION ALL SELECT 11 AS test_number, 853 AS product_id 
UNION ALL SELECT 11 AS test_number, 689 AS product_id 
UNION ALL SELECT 11 AS test_number, 850 AS product_id 
UNION ALL SELECT 11 AS test_number, 226 AS product_id 
UNION ALL SELECT 11 AS test_number, 10 AS product_id 
UNION ALL SELECT 11 AS test_number, 800 AS product_id 
UNION ALL SELECT 11 AS test_number, 6 AS product_id 
UNION ALL SELECT 11 AS test_number, 940 AS product_id 
UNION ALL SELECT 11 AS test_number, 385 AS product_id 
UNION ALL SELECT 11 AS test_number, 472 AS product_id 
UNION ALL SELECT 11 AS test_number, 977 AS product_id 
UNION ALL SELECT 11 AS test_number, 239 AS product_id 
UNION ALL SELECT 11 AS test_number, 652 AS product_id 
UNION ALL SELECT 11 AS test_number, 495 AS product_id 
UNION ALL SELECT 11 AS test_number, 709 AS product_id 
UNION ALL SELECT 11 AS test_number, 919 AS product_id 
UNION ALL SELECT 11 AS test_number, 421 AS product_id 
UNION ALL SELECT 11 AS test_number, 69 AS product_id 
UNION ALL SELECT 11 AS test_number, 794 AS product_id 
UNION ALL SELECT 11 AS test_number, 966 AS product_id 
UNION ALL SELECT 11 AS test_number, 506 AS product_id 
UNION ALL SELECT 11 AS test_number, 165 AS product_id 
UNION ALL SELECT 11 AS test_number, 190 AS product_id 
UNION ALL SELECT 11 AS test_number, 82 AS product_id 
UNION ALL SELECT 11 AS test_number, 68 AS product_id 
UNION ALL SELECT 11 AS test_number, 524 AS product_id 

UNION ALL SELECT 12 AS test_number, 574 AS product_id 
UNION ALL SELECT 12 AS test_number, 451 AS product_id 
UNION ALL SELECT 12 AS test_number, 716 AS product_id 
UNION ALL SELECT 12 AS test_number, 307 AS product_id 
UNION ALL SELECT 12 AS test_number, 729 AS product_id 
UNION ALL SELECT 12 AS test_number, 607 AS product_id 
UNION ALL SELECT 12 AS test_number, 392 AS product_id 
UNION ALL SELECT 12 AS test_number, 260 AS product_id 
UNION ALL SELECT 12 AS test_number, 565 AS product_id 
UNION ALL SELECT 12 AS test_number, 652 AS product_id 
UNION ALL SELECT 12 AS test_number, 830 AS product_id 
UNION ALL SELECT 12 AS test_number, 95 AS product_id 
UNION ALL SELECT 12 AS test_number, 97 AS product_id 
UNION ALL SELECT 12 AS test_number, 150 AS product_id 
UNION ALL SELECT 12 AS test_number, 656 AS product_id 
UNION ALL SELECT 12 AS test_number, 364 AS product_id 
UNION ALL SELECT 12 AS test_number, 309 AS product_id 
UNION ALL SELECT 12 AS test_number, 866 AS product_id 
UNION ALL SELECT 12 AS test_number, 5 AS product_id 
UNION ALL SELECT 12 AS test_number, 694 AS product_id 
UNION ALL SELECT 12 AS test_number, 755 AS product_id 
UNION ALL SELECT 12 AS test_number, 724 AS product_id 
UNION ALL SELECT 12 AS test_number, 242 AS product_id 
UNION ALL SELECT 12 AS test_number, 618 AS product_id 
UNION ALL SELECT 12 AS test_number, 52 AS product_id 
UNION ALL SELECT 12 AS test_number, 328 AS product_id 
UNION ALL SELECT 12 AS test_number, 583 AS product_id 
UNION ALL SELECT 12 AS test_number, 232 AS product_id 
UNION ALL SELECT 12 AS test_number, 623 AS product_id 
UNION ALL SELECT 12 AS test_number, 736 AS product_id 
UNION ALL SELECT 12 AS test_number, 49 AS product_id 
UNION ALL SELECT 12 AS test_number, 627 AS product_id 

UNION ALL SELECT 13 AS test_number, 642 AS product_id 
UNION ALL SELECT 13 AS test_number, 218 AS product_id 
UNION ALL SELECT 13 AS test_number, 823 AS product_id 
UNION ALL SELECT 13 AS test_number, 867 AS product_id 
UNION ALL SELECT 13 AS test_number, 8 AS product_id 
UNION ALL SELECT 13 AS test_number, 636 AS product_id 
UNION ALL SELECT 13 AS test_number, 888 AS product_id 
UNION ALL SELECT 13 AS test_number, 958 AS product_id 
UNION ALL SELECT 13 AS test_number, 538 AS product_id 
UNION ALL SELECT 13 AS test_number, 411 AS product_id 
UNION ALL SELECT 13 AS test_number, 870 AS product_id 
UNION ALL SELECT 13 AS test_number, 903 AS product_id 
UNION ALL SELECT 13 AS test_number, 159 AS product_id 
UNION ALL SELECT 13 AS test_number, 748 AS product_id 
UNION ALL SELECT 13 AS test_number, 595 AS product_id 
UNION ALL SELECT 13 AS test_number, 529 AS product_id 
UNION ALL SELECT 13 AS test_number, 47 AS product_id 
UNION ALL SELECT 13 AS test_number, 769 AS product_id 
UNION ALL SELECT 13 AS test_number, 939 AS product_id 
UNION ALL SELECT 13 AS test_number, 517 AS product_id 
UNION ALL SELECT 13 AS test_number, 290 AS product_id 
UNION ALL SELECT 13 AS test_number, 861 AS product_id 
UNION ALL SELECT 13 AS test_number, 702 AS product_id 
UNION ALL SELECT 13 AS test_number, 23 AS product_id 
UNION ALL SELECT 13 AS test_number, 554 AS product_id 
UNION ALL SELECT 13 AS test_number, 469 AS product_id 
UNION ALL SELECT 13 AS test_number, 257 AS product_id 
UNION ALL SELECT 13 AS test_number, 14 AS product_id 

UNION ALL SELECT 14 AS test_number, 914 AS product_id 
UNION ALL SELECT 14 AS test_number, 117 AS product_id 
UNION ALL SELECT 14 AS test_number, 368 AS product_id 
UNION ALL SELECT 14 AS test_number, 251 AS product_id 
UNION ALL SELECT 14 AS test_number, 348 AS product_id 
UNION ALL SELECT 14 AS test_number, 669 AS product_id 
UNION ALL SELECT 14 AS test_number, 33 AS product_id 
UNION ALL SELECT 14 AS test_number, 599 AS product_id 
UNION ALL SELECT 14 AS test_number, 183 AS product_id 
UNION ALL SELECT 14 AS test_number, 527 AS product_id 
UNION ALL SELECT 14 AS test_number, 252 AS product_id 
UNION ALL SELECT 14 AS test_number, 383 AS product_id 
UNION ALL SELECT 14 AS test_number, 131 AS product_id 
UNION ALL SELECT 14 AS test_number, 674 AS product_id 
UNION ALL SELECT 14 AS test_number, 583 AS product_id 
UNION ALL SELECT 14 AS test_number, 837 AS product_id 
UNION ALL SELECT 14 AS test_number, 270 AS product_id 
UNION ALL SELECT 14 AS test_number, 972 AS product_id 
UNION ALL SELECT 14 AS test_number, 618 AS product_id 
UNION ALL SELECT 14 AS test_number, 398 AS product_id 
UNION ALL SELECT 14 AS test_number, 973 AS product_id 
UNION ALL SELECT 14 AS test_number, 817 AS product_id 
UNION ALL SELECT 14 AS test_number, 642 AS product_id 
UNION ALL SELECT 14 AS test_number, 216 AS product_id 
UNION ALL SELECT 14 AS test_number, 648 AS product_id 
UNION ALL SELECT 14 AS test_number, 531 AS product_id 
UNION ALL SELECT 14 AS test_number, 62 AS product_id 
UNION ALL SELECT 14 AS test_number, 602 AS product_id 
UNION ALL SELECT 14 AS test_number, 258 AS product_id 
UNION ALL SELECT 14 AS test_number, 834 AS product_id 
UNION ALL SELECT 14 AS test_number, 753 AS product_id 
UNION ALL SELECT 14 AS test_number, 793 AS product_id 
UNION ALL SELECT 14 AS test_number, 847 AS product_id 
UNION ALL SELECT 14 AS test_number, 424 AS product_id 
UNION ALL SELECT 14 AS test_number, 403 AS product_id 

UNION ALL SELECT 15 AS test_number, 576 AS product_id 
UNION ALL SELECT 15 AS test_number, 682 AS product_id 
UNION ALL SELECT 15 AS test_number, 888 AS product_id 
UNION ALL SELECT 15 AS test_number, 372 AS product_id 
UNION ALL SELECT 15 AS test_number, 675 AS product_id 
UNION ALL SELECT 15 AS test_number, 101 AS product_id 
UNION ALL SELECT 15 AS test_number, 640 AS product_id 
UNION ALL SELECT 15 AS test_number, 998 AS product_id 
UNION ALL SELECT 15 AS test_number, 950 AS product_id 
UNION ALL SELECT 15 AS test_number, 260 AS product_id 
UNION ALL SELECT 15 AS test_number, 971 AS product_id 
UNION ALL SELECT 15 AS test_number, 93 AS product_id 
UNION ALL SELECT 15 AS test_number, 628 AS product_id 
UNION ALL SELECT 15 AS test_number, 995 AS product_id 
UNION ALL SELECT 15 AS test_number, 847 AS product_id 
UNION ALL SELECT 15 AS test_number, 199 AS product_id 
UNION ALL SELECT 15 AS test_number, 105 AS product_id 
UNION ALL SELECT 15 AS test_number, 547 AS product_id 
UNION ALL SELECT 15 AS test_number, 68 AS product_id 
UNION ALL SELECT 15 AS test_number, 747 AS product_id 
UNION ALL SELECT 15 AS test_number, 116 AS product_id 
UNION ALL SELECT 15 AS test_number, 724 AS product_id 
UNION ALL SELECT 15 AS test_number, 284 AS product_id 
UNION ALL SELECT 15 AS test_number, 200 AS product_id 
UNION ALL SELECT 15 AS test_number, 655 AS product_id 
UNION ALL SELECT 15 AS test_number, 7 AS product_id 
UNION ALL SELECT 15 AS test_number, 807 AS product_id 
UNION ALL SELECT 15 AS test_number, 12 AS product_id 
UNION ALL SELECT 15 AS test_number, 763 AS product_id 
UNION ALL SELECT 15 AS test_number, 62 AS product_id 
UNION ALL SELECT 15 AS test_number, 245 AS product_id 
UNION ALL SELECT 15 AS test_number, 786 AS product_id 
UNION ALL SELECT 15 AS test_number, 394 AS product_id 
UNION ALL SELECT 15 AS test_number, 890 AS product_id 
UNION ALL SELECT 15 AS test_number, 122 AS product_id 
UNION ALL SELECT 15 AS test_number, 435 AS product_id 
UNION ALL SELECT 15 AS test_number, 926 AS product_id 
UNION ALL SELECT 15 AS test_number, 257 AS product_id 

UNION ALL SELECT 16 AS test_number, 877 AS product_id 
UNION ALL SELECT 16 AS test_number, 544 AS product_id 
UNION ALL SELECT 16 AS test_number, 600 AS product_id 
UNION ALL SELECT 16 AS test_number, 941 AS product_id 
UNION ALL SELECT 16 AS test_number, 518 AS product_id 
UNION ALL SELECT 16 AS test_number, 905 AS product_id 
UNION ALL SELECT 16 AS test_number, 331 AS product_id 
UNION ALL SELECT 16 AS test_number, 463 AS product_id 
UNION ALL SELECT 16 AS test_number, 853 AS product_id 
UNION ALL SELECT 16 AS test_number, 818 AS product_id 
UNION ALL SELECT 16 AS test_number, 195 AS product_id 
UNION ALL SELECT 16 AS test_number, 865 AS product_id 
UNION ALL SELECT 16 AS test_number, 975 AS product_id 
UNION ALL SELECT 16 AS test_number, 278 AS product_id 
UNION ALL SELECT 16 AS test_number, 36 AS product_id 
UNION ALL SELECT 16 AS test_number, 554 AS product_id 
UNION ALL SELECT 16 AS test_number, 798 AS product_id 
UNION ALL SELECT 16 AS test_number, 204 AS product_id 
UNION ALL SELECT 16 AS test_number, 23 AS product_id 
UNION ALL SELECT 16 AS test_number, 129 AS product_id 
UNION ALL SELECT 16 AS test_number, 707 AS product_id 
UNION ALL SELECT 16 AS test_number, 383 AS product_id 
UNION ALL SELECT 16 AS test_number, 164 AS product_id 
UNION ALL SELECT 16 AS test_number, 432 AS product_id 
UNION ALL SELECT 16 AS test_number, 981 AS product_id 
UNION ALL SELECT 16 AS test_number, 582 AS product_id 
UNION ALL SELECT 16 AS test_number, 269 AS product_id 
UNION ALL SELECT 16 AS test_number, 761 AS product_id 
UNION ALL SELECT 16 AS test_number, 175 AS product_id 
UNION ALL SELECT 16 AS test_number, 541 AS product_id 
UNION ALL SELECT 16 AS test_number, 31 AS product_id 
UNION ALL SELECT 16 AS test_number, 288 AS product_id 
UNION ALL SELECT 16 AS test_number, 522 AS product_id 
UNION ALL SELECT 16 AS test_number, 263 AS product_id 
UNION ALL SELECT 16 AS test_number, 208 AS product_id 
UNION ALL SELECT 16 AS test_number, 948 AS product_id 
UNION ALL SELECT 16 AS test_number, 369 AS product_id 

UNION ALL SELECT 17 AS test_number, 208 AS product_id 
UNION ALL SELECT 17 AS test_number, 735 AS product_id 
UNION ALL SELECT 17 AS test_number, 859 AS product_id 
UNION ALL SELECT 17 AS test_number, 412 AS product_id 
UNION ALL SELECT 17 AS test_number, 872 AS product_id 
UNION ALL SELECT 17 AS test_number, 891 AS product_id 
UNION ALL SELECT 17 AS test_number, 693 AS product_id 
UNION ALL SELECT 17 AS test_number, 650 AS product_id 
UNION ALL SELECT 17 AS test_number, 948 AS product_id 
UNION ALL SELECT 17 AS test_number, 361 AS product_id 
UNION ALL SELECT 17 AS test_number, 945 AS product_id 
UNION ALL SELECT 17 AS test_number, 777 AS product_id 
UNION ALL SELECT 17 AS test_number, 346 AS product_id 
UNION ALL SELECT 17 AS test_number, 665 AS product_id 
UNION ALL SELECT 17 AS test_number, 843 AS product_id 
UNION ALL SELECT 17 AS test_number, 842 AS product_id 
UNION ALL SELECT 17 AS test_number, 837 AS product_id 
UNION ALL SELECT 17 AS test_number, 156 AS product_id 
UNION ALL SELECT 17 AS test_number, 727 AS product_id 
UNION ALL SELECT 17 AS test_number, 672 AS product_id 
UNION ALL SELECT 17 AS test_number, 308 AS product_id 
UNION ALL SELECT 17 AS test_number, 814 AS product_id 
UNION ALL SELECT 17 AS test_number, 987 AS product_id 
UNION ALL SELECT 17 AS test_number, 403 AS product_id 
UNION ALL SELECT 17 AS test_number, 696 AS product_id 
UNION ALL SELECT 17 AS test_number, 413 AS product_id 
UNION ALL SELECT 17 AS test_number, 600 AS product_id 
UNION ALL SELECT 17 AS test_number, 259 AS product_id 
UNION ALL SELECT 17 AS test_number, 583 AS product_id 
UNION ALL SELECT 17 AS test_number, 977 AS product_id 
UNION ALL SELECT 17 AS test_number, 587 AS product_id 
UNION ALL SELECT 17 AS test_number, 184 AS product_id 
UNION ALL SELECT 17 AS test_number, 329 AS product_id 
UNION ALL SELECT 17 AS test_number, 170 AS product_id 
UNION ALL SELECT 17 AS test_number, 381 AS product_id 
UNION ALL SELECT 17 AS test_number, 957 AS product_id 
UNION ALL SELECT 17 AS test_number, 867 AS product_id 
UNION ALL SELECT 17 AS test_number, 67 AS product_id 
UNION ALL SELECT 17 AS test_number, 808 AS product_id 
UNION ALL SELECT 17 AS test_number, 597 AS product_id 
UNION ALL SELECT 17 AS test_number, 14 AS product_id 
UNION ALL SELECT 17 AS test_number, 161 AS product_id 
UNION ALL SELECT 17 AS test_number, 200 AS product_id 
UNION ALL SELECT 17 AS test_number, 734 AS product_id 
UNION ALL SELECT 17 AS test_number, 841 AS product_id 
UNION ALL SELECT 17 AS test_number, 290 AS product_id 
UNION ALL SELECT 17 AS test_number, 150 AS product_id 
UNION ALL SELECT 17 AS test_number, 373 AS product_id 

UNION ALL SELECT 18 AS test_number, 969 AS product_id 
UNION ALL SELECT 18 AS test_number, 848 AS product_id 
UNION ALL SELECT 18 AS test_number, 258 AS product_id 
UNION ALL SELECT 18 AS test_number, 598 AS product_id 
UNION ALL SELECT 18 AS test_number, 991 AS product_id 
UNION ALL SELECT 18 AS test_number, 8 AS product_id 
UNION ALL SELECT 18 AS test_number, 297 AS product_id 
UNION ALL SELECT 18 AS test_number, 300 AS product_id 
UNION ALL SELECT 18 AS test_number, 599 AS product_id 
UNION ALL SELECT 18 AS test_number, 217 AS product_id 
UNION ALL SELECT 18 AS test_number, 638 AS product_id 
UNION ALL SELECT 18 AS test_number, 981 AS product_id 
UNION ALL SELECT 18 AS test_number, 976 AS product_id 
UNION ALL SELECT 18 AS test_number, 320 AS product_id 
UNION ALL SELECT 18 AS test_number, 601 AS product_id 
UNION ALL SELECT 18 AS test_number, 417 AS product_id 
UNION ALL SELECT 18 AS test_number, 648 AS product_id 
UNION ALL SELECT 18 AS test_number, 525 AS product_id 
UNION ALL SELECT 18 AS test_number, 924 AS product_id 
UNION ALL SELECT 18 AS test_number, 966 AS product_id 
UNION ALL SELECT 18 AS test_number, 206 AS product_id 
UNION ALL SELECT 18 AS test_number, 360 AS product_id 
UNION ALL SELECT 18 AS test_number, 465 AS product_id 
UNION ALL SELECT 18 AS test_number, 372 AS product_id 
UNION ALL SELECT 18 AS test_number, 610 AS product_id 
UNION ALL SELECT 18 AS test_number, 792 AS product_id 
UNION ALL SELECT 18 AS test_number, 606 AS product_id 
UNION ALL SELECT 18 AS test_number, 858 AS product_id 
UNION ALL SELECT 18 AS test_number, 123 AS product_id 
UNION ALL SELECT 18 AS test_number, 179 AS product_id 
UNION ALL SELECT 18 AS test_number, 577 AS product_id 
UNION ALL SELECT 18 AS test_number, 349 AS product_id 
UNION ALL SELECT 18 AS test_number, 449 AS product_id 
UNION ALL SELECT 18 AS test_number, 428 AS product_id 
UNION ALL SELECT 18 AS test_number, 574 AS product_id 
UNION ALL SELECT 18 AS test_number, 59 AS product_id 
UNION ALL SELECT 18 AS test_number, 869 AS product_id 
UNION ALL SELECT 18 AS test_number, 902 AS product_id 
UNION ALL SELECT 18 AS test_number, 307 AS product_id 
UNION ALL SELECT 18 AS test_number, 999 AS product_id 
UNION ALL SELECT 18 AS test_number, 215 AS product_id 
UNION ALL SELECT 18 AS test_number, 242 AS product_id 
UNION ALL SELECT 18 AS test_number, 497 AS product_id 

UNION ALL SELECT 19 AS test_number, 662 AS product_id 
UNION ALL SELECT 19 AS test_number, 128 AS product_id 
UNION ALL SELECT 19 AS test_number, 38 AS product_id 
UNION ALL SELECT 19 AS test_number, 771 AS product_id 
UNION ALL SELECT 19 AS test_number, 49 AS product_id 
UNION ALL SELECT 19 AS test_number, 596 AS product_id 
UNION ALL SELECT 19 AS test_number, 477 AS product_id 
UNION ALL SELECT 19 AS test_number, 449 AS product_id 
UNION ALL SELECT 19 AS test_number, 869 AS product_id 
UNION ALL SELECT 19 AS test_number, 610 AS product_id 
UNION ALL SELECT 19 AS test_number, 562 AS product_id 
UNION ALL SELECT 19 AS test_number, 240 AS product_id 
UNION ALL SELECT 19 AS test_number, 863 AS product_id 
UNION ALL SELECT 19 AS test_number, 953 AS product_id 
UNION ALL SELECT 19 AS test_number, 54 AS product_id 
UNION ALL SELECT 19 AS test_number, 15 AS product_id 
UNION ALL SELECT 19 AS test_number, 198 AS product_id 
UNION ALL SELECT 19 AS test_number, 875 AS product_id 
UNION ALL SELECT 19 AS test_number, 153 AS product_id 
UNION ALL SELECT 19 AS test_number, 822 AS product_id 
UNION ALL SELECT 19 AS test_number, 210 AS product_id 
UNION ALL SELECT 19 AS test_number, 22 AS product_id 
UNION ALL SELECT 19 AS test_number, 686 AS product_id 
UNION ALL SELECT 19 AS test_number, 490 AS product_id 
UNION ALL SELECT 19 AS test_number, 497 AS product_id 
UNION ALL SELECT 19 AS test_number, 809 AS product_id 
UNION ALL SELECT 19 AS test_number, 144 AS product_id 
UNION ALL SELECT 19 AS test_number, 927 AS product_id 
UNION ALL SELECT 19 AS test_number, 659 AS product_id 
UNION ALL SELECT 19 AS test_number, 512 AS product_id 
UNION ALL SELECT 19 AS test_number, 514 AS product_id 
UNION ALL SELECT 19 AS test_number, 886 AS product_id 
UNION ALL SELECT 19 AS test_number, 993 AS product_id 
UNION ALL SELECT 19 AS test_number, 184 AS product_id 
UNION ALL SELECT 19 AS test_number, 118 AS product_id 
UNION ALL SELECT 19 AS test_number, 577 AS product_id 
UNION ALL SELECT 19 AS test_number, 91 AS product_id 
UNION ALL SELECT 19 AS test_number, 170 AS product_id 
UNION ALL SELECT 19 AS test_number, 136 AS product_id 
UNION ALL SELECT 19 AS test_number, 637 AS product_id 
UNION ALL SELECT 19 AS test_number, 821 AS product_id 
UNION ALL SELECT 19 AS test_number, 167 AS product_id 
UNION ALL SELECT 19 AS test_number, 919 AS product_id 

UNION ALL SELECT 20 AS test_number, 187 AS product_id 
UNION ALL SELECT 20 AS test_number, 47 AS product_id 
UNION ALL SELECT 20 AS test_number, 276 AS product_id 
UNION ALL SELECT 20 AS test_number, 221 AS product_id 
UNION ALL SELECT 20 AS test_number, 316 AS product_id 
UNION ALL SELECT 20 AS test_number, 292 AS product_id 
UNION ALL SELECT 20 AS test_number, 383 AS product_id 
UNION ALL SELECT 20 AS test_number, 894 AS product_id 
UNION ALL SELECT 20 AS test_number, 165 AS product_id 
UNION ALL SELECT 20 AS test_number, 49 AS product_id 
UNION ALL SELECT 20 AS test_number, 149 AS product_id 
UNION ALL SELECT 20 AS test_number, 288 AS product_id 
UNION ALL SELECT 20 AS test_number, 307 AS product_id 
UNION ALL SELECT 20 AS test_number, 177 AS product_id 
UNION ALL SELECT 20 AS test_number, 674 AS product_id 
UNION ALL SELECT 20 AS test_number, 697 AS product_id 
UNION ALL SELECT 20 AS test_number, 835 AS product_id 
UNION ALL SELECT 20 AS test_number, 962 AS product_id 
UNION ALL SELECT 20 AS test_number, 325 AS product_id 
UNION ALL SELECT 20 AS test_number, 502 AS product_id 
UNION ALL SELECT 20 AS test_number, 244 AS product_id 
UNION ALL SELECT 20 AS test_number, 523 AS product_id 
UNION ALL SELECT 20 AS test_number, 494 AS product_id 
UNION ALL SELECT 20 AS test_number, 377 AS product_id 
UNION ALL SELECT 20 AS test_number, 695 AS product_id 
UNION ALL SELECT 20 AS test_number, 876 AS product_id 
UNION ALL SELECT 20 AS test_number, 896 AS product_id 
UNION ALL SELECT 20 AS test_number, 482 AS product_id 
UNION ALL SELECT 20 AS test_number, 368 AS product_id 
UNION ALL SELECT 20 AS test_number, 872 AS product_id 
UNION ALL SELECT 20 AS test_number, 540 AS product_id 
UNION ALL SELECT 20 AS test_number, 175 AS product_id 
UNION ALL SELECT 20 AS test_number, 211 AS product_id 
UNION ALL SELECT 20 AS test_number, 104 AS product_id 
UNION ALL SELECT 20 AS test_number, 758 AS product_id 
UNION ALL SELECT 20 AS test_number, 16 AS product_id 
UNION ALL SELECT 20 AS test_number, 854 AS product_id 
UNION ALL SELECT 20 AS test_number, 3 AS product_id 
UNION ALL SELECT 20 AS test_number, 629 AS product_id 
UNION ALL SELECT 20 AS test_number, 850 AS product_id 
UNION ALL SELECT 20 AS test_number, 310 AS product_id 
UNION ALL SELECT 20 AS test_number, 721 AS product_id 
UNION ALL SELECT 20 AS test_number, 701 AS product_id 
UNION ALL SELECT 20 AS test_number, 761 AS product_id 
UNION ALL SELECT 20 AS test_number, 145 AS product_id 
UNION ALL SELECT 20 AS test_number, 639 AS product_id 
UNION ALL SELECT 20 AS test_number, 404 AS product_id 
UNION ALL SELECT 20 AS test_number, 838 AS product_id 
UNION ALL SELECT 20 AS test_number, 204 AS product_id 

UNION ALL SELECT 21 AS test_number, 584 AS product_id 
UNION ALL SELECT 21 AS test_number, 31 AS product_id 
UNION ALL SELECT 21 AS test_number, 132 AS product_id 
UNION ALL SELECT 21 AS test_number, 474 AS product_id 
UNION ALL SELECT 21 AS test_number, 797 AS product_id 
UNION ALL SELECT 21 AS test_number, 72 AS product_id 
UNION ALL SELECT 21 AS test_number, 966 AS product_id 
UNION ALL SELECT 21 AS test_number, 16 AS product_id 
UNION ALL SELECT 21 AS test_number, 700 AS product_id 
UNION ALL SELECT 21 AS test_number, 481 AS product_id 
UNION ALL SELECT 21 AS test_number, 243 AS product_id 
UNION ALL SELECT 21 AS test_number, 750 AS product_id 
UNION ALL SELECT 21 AS test_number, 470 AS product_id 
UNION ALL SELECT 21 AS test_number, 11 AS product_id 
UNION ALL SELECT 21 AS test_number, 115 AS product_id 
UNION ALL SELECT 21 AS test_number, 153 AS product_id 
UNION ALL SELECT 21 AS test_number, 136 AS product_id 
UNION ALL SELECT 21 AS test_number, 691 AS product_id 
UNION ALL SELECT 21 AS test_number, 237 AS product_id 
UNION ALL SELECT 21 AS test_number, 441 AS product_id 
UNION ALL SELECT 21 AS test_number, 709 AS product_id 
UNION ALL SELECT 21 AS test_number, 62 AS product_id 
UNION ALL SELECT 21 AS test_number, 89 AS product_id 
UNION ALL SELECT 21 AS test_number, 293 AS product_id 
UNION ALL SELECT 21 AS test_number, 144 AS product_id 
UNION ALL SELECT 21 AS test_number, 634 AS product_id 
UNION ALL SELECT 21 AS test_number, 1000 AS product_id 
UNION ALL SELECT 21 AS test_number, 318 AS product_id 
UNION ALL SELECT 21 AS test_number, 757 AS product_id 
UNION ALL SELECT 21 AS test_number, 605 AS product_id 
UNION ALL SELECT 21 AS test_number, 412 AS product_id 
UNION ALL SELECT 21 AS test_number, 430 AS product_id 
UNION ALL SELECT 21 AS test_number, 22 AS product_id 
UNION ALL SELECT 21 AS test_number, 419 AS product_id 
UNION ALL SELECT 21 AS test_number, 754 AS product_id 
UNION ALL SELECT 21 AS test_number, 581 AS product_id 
UNION ALL SELECT 21 AS test_number, 963 AS product_id 
UNION ALL SELECT 21 AS test_number, 617 AS product_id 
UNION ALL SELECT 21 AS test_number, 319 AS product_id 
UNION ALL SELECT 21 AS test_number, 781 AS product_id 
UNION ALL SELECT 21 AS test_number, 991 AS product_id 
UNION ALL SELECT 21 AS test_number, 716 AS product_id 
UNION ALL SELECT 21 AS test_number, 258 AS product_id 
UNION ALL SELECT 21 AS test_number, 782 AS product_id 

UNION ALL SELECT 22 AS test_number, 584 AS product_id 
UNION ALL SELECT 22 AS test_number, 31 AS product_id 
UNION ALL SELECT 22 AS test_number, 132 AS product_id 
UNION ALL SELECT 22 AS test_number, 474 AS product_id 
UNION ALL SELECT 22 AS test_number, 797 AS product_id 
UNION ALL SELECT 22 AS test_number, 72 AS product_id 
UNION ALL SELECT 22 AS test_number, 966 AS product_id 
UNION ALL SELECT 22 AS test_number, 16 AS product_id 
UNION ALL SELECT 22 AS test_number, 700 AS product_id 
UNION ALL SELECT 22 AS test_number, 481 AS product_id 
UNION ALL SELECT 22 AS test_number, 243 AS product_id 
UNION ALL SELECT 22 AS test_number, 750 AS product_id 
UNION ALL SELECT 22 AS test_number, 470 AS product_id 
UNION ALL SELECT 22 AS test_number, 11 AS product_id 
UNION ALL SELECT 22 AS test_number, 115 AS product_id 
UNION ALL SELECT 22 AS test_number, 153 AS product_id 
UNION ALL SELECT 22 AS test_number, 136 AS product_id 
UNION ALL SELECT 22 AS test_number, 691 AS product_id 
UNION ALL SELECT 22 AS test_number, 237 AS product_id 
UNION ALL SELECT 22 AS test_number, 441 AS product_id 
UNION ALL SELECT 22 AS test_number, 709 AS product_id 
UNION ALL SELECT 22 AS test_number, 62 AS product_id 
UNION ALL SELECT 22 AS test_number, 89 AS product_id 
UNION ALL SELECT 22 AS test_number, 293 AS product_id 
UNION ALL SELECT 22 AS test_number, 144 AS product_id 
UNION ALL SELECT 22 AS test_number, 634 AS product_id 
UNION ALL SELECT 22 AS test_number, 1000 AS product_id 
UNION ALL SELECT 22 AS test_number, 318 AS product_id 
UNION ALL SELECT 22 AS test_number, 757 AS product_id 
UNION ALL SELECT 22 AS test_number, 605 AS product_id 
UNION ALL SELECT 22 AS test_number, 412 AS product_id 
UNION ALL SELECT 22 AS test_number, 430 AS product_id 
UNION ALL SELECT 22 AS test_number, 22 AS product_id 
UNION ALL SELECT 22 AS test_number, 419 AS product_id 
UNION ALL SELECT 22 AS test_number, 754 AS product_id 
UNION ALL SELECT 22 AS test_number, 581 AS product_id 
UNION ALL SELECT 22 AS test_number, 963 AS product_id 
UNION ALL SELECT 22 AS test_number, 617 AS product_id 
UNION ALL SELECT 22 AS test_number, 319 AS product_id 
UNION ALL SELECT 22 AS test_number, 781 AS product_id 
UNION ALL SELECT 22 AS test_number, 991 AS product_id 
UNION ALL SELECT 22 AS test_number, 716 AS product_id 
UNION ALL SELECT 22 AS test_number, 258 AS product_id 
UNION ALL SELECT 22 AS test_number, 782 AS product_id 
),
counter AS ( SELECT @test_number := IF(@test_number IS NULL, 0, @test_number + 1) AS test_number )
SELECT literal_table.product_id AS product_id
FROM literal_table, counter
WHERE counter.test_number = literal_table.test_number;